# Generated by Django 4.2.5 on 2023-09-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='time',
            field=models.TimeField(auto_now=True, verbose_name='Время рассылки'),
        ),
    ]
