# Generated by Django 4.2.5 on 2023-09-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='periodicity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Периодичность рассылки'),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Статус рассылки'),
        ),
    ]
