# Generated by Django 4.2.5 on 2023-09-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_service_periodicity_alter_service_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='time',
            field=models.TimeField(verbose_name='Время рассылки'),
        ),
    ]
