# Generated by Django 4.2.5 on 2023-10-06 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_mailing_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('set_is_activ', 'Can active mailing')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.RenameField(
            model_name='mailing',
            old_name='is_activ',
            new_name='is_active',
        ),
    ]
