# Generated by Django 4.2.5 on 2023-09-18 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_service_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='periodicity',
        ),
        migrations.RemoveField(
            model_name='service',
            name='status',
        ),
    ]
