# Generated by Django 4.2.5 on 2023-09-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_remove_service_periodicity_remove_service_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='time',
            field=models.TimeField(auto_now=True, verbose_name='Время рассылки'),
        ),
    ]
