# Generated by Django 4.2.5 on 2023-09-20 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_alter_service_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='time',
        ),
    ]
