# Generated by Django 4.2.5 on 2023-09-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_remove_service_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.BooleanField(verbose_name='Раз в день')),
                ('week', models.BooleanField(verbose_name='Раз в неделю')),
                ('month', models.BooleanField(verbose_name='Раз в месяц')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='finish',
            field=models.TimeField(auto_now=True, verbose_name='Время окончания рассылки'),
        ),
        migrations.AddField(
            model_name='service',
            name='start',
            field=models.TimeField(auto_now=True, verbose_name='Время начала рассылки'),
        ),
    ]
