# Generated by Django 4.2.5 on 2023-10-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='next_run',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время следующей рассылки'),
        ),
    ]
