# Generated by Django 4.2.5 on 2023-10-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_mailing_next_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='next_run',
            field=models.DateField(blank=True, null=True, verbose_name='Дата следующей рассылки'),
        ),
    ]
