# Generated by Django 4.2.5 on 2023-09-20 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_periodicity_service_finish_service_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='periodicity',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='service.periodicity', verbose_name='Периодичность рассылки'),
        ),
    ]
