# Generated by Django 4.2.5 on 2023-09-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_alter_service_periodicity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='periodicity',
        ),
        migrations.AddField(
            model_name='service',
            name='day',
            field=models.BooleanField(default=False, verbose_name='Раз в день'),
        ),
        migrations.AddField(
            model_name='service',
            name='month',
            field=models.BooleanField(default=False, verbose_name='Раз в месяц'),
        ),
        migrations.AddField(
            model_name='service',
            name='week',
            field=models.BooleanField(default=False, verbose_name='Раз в неделю'),
        ),
        migrations.DeleteModel(
            name='Periodicity',
        ),
    ]
