# Generated by Django 4.2.5 on 2023-10-08 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_alter_mailing_next_run'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='is_active',
        ),
    ]
