# Generated by Django 4.2.5 on 2023-09-20 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_remove_service_periodicity_service_day_service_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='day',
        ),
        migrations.RemoveField(
            model_name='service',
            name='month',
        ),
        migrations.RemoveField(
            model_name='service',
            name='week',
        ),
    ]
