# Generated by Django 4.2.5 on 2023-09-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_remove_service_day_remove_service_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='day',
            field=models.BooleanField(default=False, verbose_name='Раз в день'),
        ),
        migrations.AddField(
            model_name='service',
            name='month',
            field=models.BooleanField(default=False, verbose_name='Раз в месяц'),
        ),
        migrations.AddField(
            model_name='service',
            name='week',
            field=models.BooleanField(default=False, verbose_name='Раз в неделю'),
        ),
    ]
