# Generated by Django 4.2.5 on 2023-09-20 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_service_day_service_month_service_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='log',
        ),
        migrations.AddField(
            model_name='log',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.service', verbose_name='Рассылка'),
        ),
    ]
