# Generated by Django 4.2.5 on 2023-10-08 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_alter_mailing_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.mailing', verbose_name='Рассылка'),
        ),
    ]
