# Generated by Django 4.2.5 on 2023-09-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_remove_service_log_log_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Содержимое письма'),
        ),
    ]
