# Generated by Django 4.2.5 on 2023-10-11 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_alter_log_mailing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('set_is_active_mailing', 'Can active Рассылка')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
