# Generated by Django 4.2.6 on 2023-10-14 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_alter_mailing_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ('pk',), 'permissions': [('set_is_active_mailing', 'Can active Рассылка')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
