# Generated by Django 4.2.5 on 2023-09-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_alter_service_finish_alter_service_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='finish',
            field=models.TimeField(auto_now='00:00:00', verbose_name='Время окончания рассылки'),
        ),
        migrations.AlterField(
            model_name='service',
            name='start',
            field=models.TimeField(default='00:00:00', verbose_name='Время начала рассылки'),
        ),
    ]
