# Generated by Django 4.2.5 on 2023-09-20 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0019_alter_service_finish_alter_service_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='finish',
        ),
        migrations.RemoveField(
            model_name='service',
            name='start',
        ),
    ]
