# Generated by Django 4.2.5 on 2023-09-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_remove_service_finish_remove_service_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='finish',
            field=models.TimeField(auto_now='00:00:00', verbose_name='Время окончания рассылки'),
            preserve_default='00:00:00',
        ),
        migrations.AddField(
            model_name='service',
            name='start',
            field=models.TimeField(default='00:00:00', verbose_name='Время начала рассылки'),
        ),
    ]
