# Generated by Django 4.2.5 on 2023-09-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0021_service_finish_service_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='finish',
            field=models.TimeField(default='00:00:00', verbose_name='Время окончания рассылки'),
        ),
    ]
