# Generated by Django 4.2.6 on 2023-10-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0021_alter_customer_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='message',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, verbose_name='slug'),
        ),
    ]
