# Generated by Django 4.2.5 on 2023-09-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0023_remove_service_customer_service_customers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Сервис', 'verbose_name_plural': 'Сервисы'},
        ),
        migrations.AddField(
            model_name='service',
            name='date_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время создания'),
        ),
        migrations.AlterField(
            model_name='service',
            name='customers',
            field=models.ManyToManyField(to='service.customer', verbose_name='Клиенты'),
        ),
    ]
