# Generated by Django 4.2.6 on 2023-10-16 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0023_alter_log_slug_alter_mailing_slug_alter_message_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='slug',
        ),
    ]
