# Generated by Django 4.2.5 on 2023-09-24 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0024_alter_service_options_service_date_time_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Mailing',
        ),
        migrations.AlterModelOptions(
            name='mailing',
            options={'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
