# Generated by Django 4.2.5 on 2023-10-01 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0025_rename_service_mailing_alter_mailing_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='service',
            new_name='mailing',
        ),
    ]
