# Generated by Django 4.2.5 on 2023-10-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0026_rename_service_log_mailing'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='is_activ',
            field=models.BooleanField(default=True, verbose_name='Активная'),
        ),
    ]
