# Generated by Django 4.2.6 on 2023-10-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0027_log_slug_mailing_slug_message_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='log',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='message',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug'),
        ),
    ]
